### ISSUE TITLE
Add config parameter for channel name

### ISSUE THREAD

**Issue by e3b0c442** [mongoose-os-libs/rpc-uart#1]
Hello,

When including this library, an unnamed UART RPC channel is created, effectively creating a case where nothing can be sent on the channel until after something is received, as there is no name by which to call the channel.

Per discussion in gutter (https://gitter.im/cesanta/mongoose-os?at=5c3a6b5735350772cf200504), requesting the addition of a `rpc.uart.channel_dst` option so that the channel can be named from initialization. Alternatively, automatic creation of the channel could be stopped in order that a channel could be manually created without having a second useless channel; however, this would break backward-compatibility so I believe the ability to name the automatically-opened channel to be the preferable option.

In addition, `mgos_rpc_uart_init()` (https://github.com/mongoose-os-libs/rpc-uart/blob/master/src/mgos_rpc_channel_uart.c#L314-L326) will need to be updated to read the channel name from the config struct.

Please let me know if you need more information.

**Comment by rojer** [comment]
sending a PR
